<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="2" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-15T21:22:40 IST" name="Suite" finished-at="2025-05-15T21:23:01 IST" duration-ms="21445">
    <groups>
      <group name="Purchase">
        <method signature="SubmitOrderTest.placeOrder(java.util.HashMap)[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest@6f8e8894]" name="placeOrder" class="Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
      <group name="ErrorHandleing">
        <method signature="ErrorMessageTest.loginErrorCheck()[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.ErrorMessageTest@44a59da3]" name="loginErrorCheck" class="Automation.SeleniumFrameworkDesign.Tests.ErrorMessageTest"/>
      </group> <!-- ErrorHandleing -->
    </groups>
    <test started-at="2025-05-15T21:22:40 IST" name="Submit Order Test" finished-at="2025-05-15T21:23:00 IST" duration-ms="19880">
      <class name="Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest@6f8e8894]" started-at="2025-05-15T21:22:40 IST" name="launchApplication" finished-at="2025-05-15T21:22:43 IST" duration-ms="2425" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="placeOrder(java.util.HashMap)[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest@6f8e8894]" started-at="2025-05-15T21:22:43 IST" name="placeOrder" data-provider="getData" finished-at="2025-05-15T21:22:46 IST" duration-ms="2833" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Tani@2613, email=taniya09@yomail.com, productName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.ElementClickInterceptedException">
            <message>
              <![CDATA[element click intercepted: Element <button _ngcontent-nrg-c33="" routerlink="/dashboard/cart" class="btn btn-custom" style="margin-top: -10px;" tabindex="0">...</button> is not clickable at point (1285, 27). Other element would receive the click: <div _ngcontent-nrg-c31="" class="ngx-spinner-overlay ng-tns-c31-1 ng-trigger ng-trigger-fadeIn ng-star-inserted" style="background-color: rgba(51, 51, 51, 0.8); z-index: 99999; position: fixed; opacity: 1;">...</div>
  (Session info: chrome=136.0.7103.113)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '23.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [61661e8c39453064e647e625b2a6f110, clickElement {id=f.268803FA60524B117D659423F72117DE.d.CFCE6A8E241B38094E23CD6DD5BCC787.e.246}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.113, chrome: {chromedriverVersion: 136.0.7103.94 (fa0be0b33deb..., userDataDir: C:\Users\RAJIB\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:65054}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:65054/devtoo..., se:cdpVersion: 136.0.7103.113, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (61661e8c39453064e647e625b2a6f110)] -> css selector: [routerlink*='cart']]
Session ID: 61661e8c39453064e647e625b2a6f110]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element <button _ngcontent-nrg-c33="" routerlink="/dashboard/cart" class="btn btn-custom" style="margin-top: -10px;" tabindex="0">...</button> is not clickable at point (1285, 27). Other element would receive the click: <div _ngcontent-nrg-c31="" class="ngx-spinner-overlay ng-tns-c31-1 ng-trigger ng-trigger-fadeIn ng-star-inserted" style="background-color: rgba(51, 51, 51, 0.8); z-index: 99999; position: fixed; opacity: 1;">...</div>
  (Session info: chrome=136.0.7103.113)
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '23.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [61661e8c39453064e647e625b2a6f110, clickElement {id=f.268803FA60524B117D659423F72117DE.d.CFCE6A8E241B38094E23CD6DD5BCC787.e.246}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 136.0.7103.113, chrome: {chromedriverVersion: 136.0.7103.94 (fa0be0b33deb..., userDataDir: C:\Users\RAJIB\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:65054}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:65054/devtoo..., se:cdpVersion: 136.0.7103.113, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (61661e8c39453064e647e625b2a6f110)] -> css selector: [routerlink*='cart']]
Session ID: 61661e8c39453064e647e625b2a6f110
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy16.click(Unknown Source)
at Automation.AbstructComponents.AbstructComponents.goToCartPage(AbstructComponents.java:54)
at Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest.placeOrder(SubmitOrderTest.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.ElementClickInterceptedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- placeOrder -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest@6f8e8894]" started-at="2025-05-15T21:22:46 IST" name="closeBrowser" finished-at="2025-05-15T21:22:47 IST" duration-ms="140" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest@6f8e8894]" started-at="2025-05-15T21:22:47 IST" name="launchApplication" finished-at="2025-05-15T21:22:50 IST" duration-ms="3464" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="placeOrder(java.util.HashMap)[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest@6f8e8894]" started-at="2025-05-15T21:22:50 IST" name="placeOrder" data-provider="getData" finished-at="2025-05-15T21:23:00 IST" duration-ms="9700" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Rajiv@123, email=rajiv09@yopmail.com, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- placeOrder -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest@6f8e8894]" started-at="2025-05-15T21:23:00 IST" name="closeBrowser" finished-at="2025-05-15T21:23:00 IST" duration-ms="128" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method signature="orderHistory()[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest@6f8e8894]" started-at="2025-05-15T21:23:00 IST" name="orderHistory" finished-at="2025-05-15T21:23:00 IST" depends-on-methods="Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest.placeOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest.orderHistory() on instance Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest@6f8e8894 depends on not successfully finished methods 
[Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest.placeOrder() on instance Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest@6f8e8894]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest.orderHistory() on instance Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest@6f8e8894 depends on not successfully finished methods 
[Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest.placeOrder() on instance Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest@6f8e8894]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistory -->
      </class> <!-- Automation.SeleniumFrameworkDesign.Tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
    <test started-at="2025-05-15T21:22:40 IST" name="Error Validation Check" finished-at="2025-05-15T21:23:01 IST" duration-ms="21445">
      <class name="Automation.SeleniumFrameworkDesign.Tests.ErrorMessageTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.ErrorMessageTest@44a59da3]" started-at="2025-05-15T21:22:40 IST" name="launchApplication" finished-at="2025-05-15T21:22:44 IST" duration-ms="3859" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorCheck()[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.ErrorMessageTest@44a59da3]" started-at="2025-05-15T21:22:44 IST" name="loginErrorCheck" finished-at="2025-05-15T21:22:45 IST" duration-ms="1559" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email and password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email and password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Automation.SeleniumFrameworkDesign.Tests.ErrorMessageTest.loginErrorCheck(ErrorMessageTest.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorCheck -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.ErrorMessageTest@44a59da3]" started-at="2025-05-15T21:22:45 IST" name="closeBrowser" finished-at="2025-05-15T21:22:46 IST" duration-ms="115" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.ErrorMessageTest@44a59da3]" started-at="2025-05-15T21:22:46 IST" name="launchApplication" finished-at="2025-05-15T21:22:49 IST" duration-ms="3736" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorCheck()[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.ErrorMessageTest@44a59da3]" started-at="2025-05-15T21:22:49 IST" name="loginErrorCheck" finished-at="2025-05-15T21:22:50 IST" duration-ms="980" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email and password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email and password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Automation.SeleniumFrameworkDesign.Tests.ErrorMessageTest.loginErrorCheck(ErrorMessageTest.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorCheck -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.ErrorMessageTest@44a59da3]" started-at="2025-05-15T21:22:51 IST" name="closeBrowser" finished-at="2025-05-15T21:22:51 IST" duration-ms="112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.ErrorMessageTest@44a59da3]" started-at="2025-05-15T21:22:51 IST" name="launchApplication" finished-at="2025-05-15T21:22:53 IST" duration-ms="1809" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorCheck()[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.ErrorMessageTest@44a59da3]" started-at="2025-05-15T21:22:53 IST" name="productErrorCheck" finished-at="2025-05-15T21:23:01 IST" duration-ms="8608" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorCheck -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Automation.SeleniumFrameworkDesign.Tests.ErrorMessageTest@44a59da3]" started-at="2025-05-15T21:23:01 IST" name="closeBrowser" finished-at="2025-05-15T21:23:01 IST" duration-ms="118" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Automation.SeleniumFrameworkDesign.Tests.ErrorMessageTest -->
    </test> <!-- Error Validation Check -->
  </suite> <!-- Suite -->
</testng-results>
